# Generated by Django 4.2.4 on 2023-10-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Cantine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='niveau',
            field=models.CharField(choices=[('P', 'Primaire'), ('C', 'Collège'), ('L', 'Lycée')], default='C', max_length=10),
        ),
    ]
