# Generated by Django 4.2.5 on 2023-10-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Cantine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeabonnes',
            name='type',
            field=models.CharField(choices=[('A', '3 jours'), ('B', 'Hebdomadaire'), ('C', 'Mensuel'), ('D', 'Trimestriel')], default='B', max_length=20, unique=True),
        ),
    ]
