# Generated by Django 4.2.5 on 2023-10-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Cantine', '0002_alter_typeabonnes_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeabonnes',
            name='price',
        ),
        migrations.AddField(
            model_name='typeabonnes',
            name='priceStudent',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='typeabonnes',
            name='priceTeacher',
            field=models.IntegerField(default=1000),
        ),
    ]
