# Generated by Django 4.2.5 on 2023-10-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Cantine', '0003_remove_typeabonnes_price_typeabonnes_pricestudent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeabonnes',
            name='type',
            field=models.CharField(choices=[('3 jours', '3 jours'), ('Hebdomadaire', 'Hebdomadaire'), ('Mensuel', 'Mensuel'), ('Trimestriel', 'Trimestriel')], default='B', max_length=20, unique=True),
        ),
    ]
