# Generated by Django 4.2.5 on 2023-10-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Cantine', '0004_alter_typeabonnes_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_abonne',
            field=models.BooleanField(default=False),
        ),
    ]
